# Generated by Django 3.0.6 on 2020-05-19 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('icon', models.CharField(max_length=32)),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('notes', models.TextField()),
            ],
        ),
    ]
